version: '3.6'
services:

  nginx:
    build: .
    container_name: docker_nginx
    ports:
        - "80:80"
        - "9000:9000"
    links:
        - mysql
    volumes:
        - ./nginx/default:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log
  
        - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
        - ../PHPFiles/:/home/php_files/

    command: /bin/bash -c "service php7.0-fpm start && service nginx start && echo "" > /var/log/nginx/access.log && echo "" > /var/log/nginx/error.log && tail -f /var/log/nginx/access.log -f /var/log/nginx/error.log -f /var/log/php7.0-fpm.log"
    environment:
        - TZ=Asia/Kolkata

  flask:
    build: Flask/
    container_name: docker_flask
    ports:
        - "81:80"
    links:
        - mysql
    volumes:
        - ../FlaskFiles/:/home/flask_files/

    command: /bin/bash -c "cd /home/flask_files/ && pip3 install -r requirements.txt && python3 app.py"
    environment:
        - TZ=Asia/Kolkata

  django:
    build: Django/
    container_name: docker_django
    ports:
        - "82:8000"
    links:
        - mysql
    volumes:
        - ../DjangoFiles/:/home/django_files/

    command: /bin/bash -c "cd /home/django_files/ && pip3 install -r requirements.txt && python3 manage.py runserver 0.0.0.0:8000"
    environment:
        - TZ=Asia/Kolkata

  node:
    image: node
    container_name: docker_node
    ports:
        - "83:8080"
    links:
        - mysql
    volumes:
        - ../NodeFiles/:/home/node_files/

    command: /bin/bash -c "cd /home/node_files/ && npm install && node index.js"
    environment:
        - TZ=Asia/Kolkata

  mysql:
    image: mysql:5.7.22
    container_name: docker_mysql
    environment:
        MYSQL_USER: user_root
        MYSQL_PASSWORD: user_root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: demo
    ports:
        - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: docker_phpmyadmin
    links:
        - mysql
    environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
    ports:
        - '8080:80'
